###### Agregar vehiculo
POST http://127.0.0.1:5001/vehiculo HTTP/1.1
Content-Type: application/json

{
    "patente":"AB2233",
    "modelo":"V16",
    "id_marca":1
}

###### Obtener todas las Vehiculos
GET http://127.0.0.1:5001/vehiculo HTTP/1.1
Content-Type: application/json


###### Obtener vehiculo por id
GET http://127.0.0.1:5001/vehiculo/1 HTTP/1.1
Content-Type: application/json

###### Actualizar vehiculo
PUT  http://127.0.0.1:5001/vehiculo/3 HTTP/1.1
Content-Type: application/json

{
    "patente":"QQ5432",
    "modelo":"V16",
    "id_marca":1
}

###### Eliminar Marca
DELETE  http://127.0.0.1:5001/vehiculo/3 HTTP/1.1
Content-Type: application/json


