###### Agregar marca
POST http://127.0.0.1:5000/marca HTTP/1.1
Content-Type: application/json

{
    "nombreMarca":"Primera marca"
}

###### Obtener todas las Marcas
GET http://127.0.0.1:5000/marca HTTP/1.1
Content-Type: application/json


###### Obtener marca por id
GET http://127.0.0.1:5000/marca/4 HTTP/1.1
Content-Type: application/json

###### Actualizar Marca
PUT  http://127.0.0.1:5000/marca HTTP/1.1
Content-Type: application/json

{
    "idMarca":3,
    "nombreMarca":"Tercera marca"
}

###### Eliminar Marca
DELETE  http://127.0.0.1:5000/marca/5 HTTP/1.1
Content-Type: application/json


